### ISSUE TITLE
extendSchema issue with query or mutation that has arguments.

### ISSUE THREAD

**Issue by wesselvdv** [alex-ald/postgraphile-nest#12]
When specifying a Query or Mutation that can accept arguments, the fieldName is used as the key for the resolver function. This results in errors when trying to execute said Mutation and Query because it can't find the associated resolver.

When changing the following code:

https://github.com/alex-ald/postgraphile-nest/blob/0281f7bbd5a3f134fe4ec4df150ff766bba47bbc/lib/factories/plugin.factory.ts#L68

To this:

```typescript
[fieldName.match(/^\w+/)[0]]: async (query, args, context, resolveInfo) => {
```

It works. The above code matches the name of the Mutation or Query. If you want a reproduction, just grab one of your examples from the wiki for extendSchema, they both have arguments and will error out.

**Comment by alex-ald** [comment]
@wesselvdv ah yes! I do see the issue. Thank you for pointing this! I'll add your fix and generate a new release.
